export const TeamList = [
  { value: "Anglia" },
  { value: "Arabia Saudyjska" },
  { value: "Argentyna" },
  { value: "Australia" },
  { value: "Belgia" },
  { value: "Brazylia" },
  { value: "Chorwacja" },
  { value: "Dania" },
  { value: "Ekwador" },
  { value: "Francja" },
  { value: "Ghana" },
  { value: "Hiszpania" },
  { value: "Holandia" },
  { value: "Iran" },
  { value: "Japonia" },
  { value: "Kamerun" },
  { value: "Kanada" },
  { value: "Katar" },
  { value: "Korea Południowa" },
  { value: "Kostaryka" },
  { value: "Maroko" },
  { value: "Meksyk" },
  { value: "Niemcy" },
  { value: "Polska" },
  { value: "Portugalia" },
  { value: "Senegal" },
  { value: "Serbia" },
  { value: "Stany Zjednoczone" },
  { value: "Szwajcaria" },
  { value: "Tunezja" },
  { value: "Urugwaj" },
  { value: "Walia" },
];
