export const TeamList = [
  { value: "Anglia", code: "en" },
  { value: "Arabia Saudyjska", code: "sa" },
  { value: "Argentyna", code: "ar" },
  { value: "Australia", code: "au" },
  { value: "Belgia", code: "be" },
  { value: "Brazylia", code: "br" },
  { value: "Chorwacja", code: "hr" },
  { value: "Dania", code: "dk" },
  { value: "Ekwador", code: "ec" },
  { value: "Francja", code: "fr" },
  { value: "Ghana", code: "gh" },
  { value: "Hiszpania", code: "es" },
  { value: "Holandia", code: "nl" },
  { value: "Iran", code: "ir" },
  { value: "Japonia", code: "jp" },
  { value: "Kamerun", code: "cm" },
  { value: "Kanada", code: "ca" },
  { value: "Katar", code: "qa" },
  { value: "Korea Południowa", code: "kr" },
  { value: "Kostaryka", code: "cr" },
  { value: "Maroko", code: "ma" },
  { value: "Meksyk", code: "mx" },
  { value: "Niemcy", code: "de" },
  { value: "Polska", code: "pl" },
  { value: "Portugalia", code: "pt" },
  { value: "Senegal", code: "sn" },
  { value: "Serbia", code: "rs" },
  { value: "Stany Zjednoczone", code: "us" },
  { value: "Szwajcaria", code: "ch" },
  { value: "Tunezja", code: "tn" },
  { value: "Urugwaj", code: "uy" },
  { value: "Walia", code: "wl" },
];
