import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9F9F9",
  },
  profile: {
    flexDirection: "row",
    marginTop: 56,
    justifyContent: "center",
    alignItems: "center",
  },
  rank: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: 60,
    color: "#FFFFFF",
    height: 52,
    lineHeight: 64,
  },
  point: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    color: "#FFFFFF",
    lineHeight: 20,
    textAlign: "center",
  },
  photo: {
    width: 88,
    height: 88,
    borderRadius: 44,
  },
  penAvatar: {
    width: 15,
    height: 15,
    position: "absolute",
    bottom: 12,
    right: 16,
  },
  nick: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 11,
    textAlign: "center",
    letterSpacing: 0.17,
    color: "#F3F4F6",
  },
  textScore: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: "5.5%",
  },
  winner: {
    marginTop: "3%",
    flexDirection: "row",
    width: "80%",
    alignItems: "center",
  },
  textWinner: {
    fontFamily: "Work-Sans-Bold",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 13,
    letterSpacing: 0.17,
    color: "#121212",
    width: 104,
    marginRight: 20,
  },
  textType: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 13,
    letterSpacing: 0.17,
    color: "rgba(0, 0, 0, 0.87)",
  },
  infoType: {
    flexDirection: "row",
    width: "80%",
    marginTop: "1%",
    alignItems: "center",
  },
  penScore: {
    width: 10,
    height: 10,
    tintColor: "rgba(0, 0, 0, 0.54)",
  },
  editScore: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "400",
    letterSpacing: 0.15,
    fontSize: 10,
    color: "rgba(97, 97, 97, 0.9)",
    marginLeft: 6,
  },
  title: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "700",
    letterSpacing: 0.17,
    fontSize: 14,
    color: "rgba(0, 0, 0, 0.87)",
    width: "80%",
    marginTop: "6%",
    marginBottom: "2%",
  },
  list: {
    justifyContent: "center",
    alignItems: "center",
  },
  flatlist: {
    width: "86%",
    height: 280,
  },
  buttons: {
    justifyContent: "center",
    alignItems: "center",
  },
  editButton: {
    height: 40,
    width: 180,
    flexDirection: "row",
    backgroundColor: "#1976D2",
    borderRadius: 120,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 6,
  },
  editText: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "500",
    letterSpacing: 0.4,
    fontSize: 14,
    color: "#FFFFFF",
    marginRight: 12,
  },
  logout: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "500",
    letterSpacing: 0.17,
    fontSize: 13,
    color: "#0D4A85",
    marginTop: 24,
  },
  containerPopup: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  popup: {
    backgroundColor: "#FFFFFF",
    width: 280,
    height: 246,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  popupTitle: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "500",
    letterSpacing: 0.15,
    fontSize: 16,
    color: "rgba(0, 0, 0, 0.87)",
    marginBottom: 16,
    marginLeft: 24,
    marginTop: 8,
  },
  popupInput: {
    width: "80%",
    height: 56,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    marginLeft: 24,
    marginBottom: 8,
  },
  popupText: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 8,
  },
  popupAnuluj: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "500",
    letterSpacing: 0.4,
    fontSize: 14,
    color: "rgba(97, 97, 97, 0.9)",
  },
  popupEdytuj: {
    fontFamily: "Work-Sans",
    fontStyle: "normal",
    fontWeight: "500",
    letterSpacing: 0.4,
    fontSize: 14,
    color: "#0D4A85",
    marginLeft: 24,
    marginRight: 16,
  },
});

export default styles;
